language: java
sudo: true
addons:
  apt:
    packages:
      - alien
    update: true
git:
  depth: 3
script:
  - mvn clean install -Dmaven.javadoc.skip=true -B -V
  - zip -r "target/GTA.SA.Savegame.Editor.app.zip" "target/gtasaveedit-3.3-SNAPSHOT/GTA SA Savegame Editor.app"
  - sudo alien --scripts -r "target/gtasaveedit_3.3~SNAPSHOT_all.deb"
  - mkdir target/deploy
  - mv target/gtasaveedit-3.3-SNAPSHOT-jar-with-dependencies.jar target/deploy
  - mv "target/GTA.SA.Savegame.Editor.app.zip" target/deploy
  - mv "target/gtasaveedit_3.3~SNAPSHOT_all.deb" target/deploy
  - mv "gtasa-savegame-editor-3.3~SNAPSHOT-2.noarch.rpm" target/deploy
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/826be7a4e8dce59091ef
    on_success: change
    on_failure: always
    on_start: never
deploy:
  provider: releases
  api_key:
    secure: lsuKoTqqWkyjemQ9QvBNIou1yOZzhqQt9c+NGYF8FcREWyPuLiDOTwrQve8skrVzwwWZVlMfyj4oef4mftN+VAEAoXWamMs3Dd9gVSoSNbGghM3KIRvBmu7n7D0EtDF3MMwGTJ2p+CQgzKWYz5uvDr0FOO3rHnjT2xyH80EgJ5Oh6seZnTpiDM+OFC2lu4iiyvC9/CAl2t+fNktBOMPbCbrL6mVcbm+5fapJPXRRfRtZS5ZOCCZKcDpjgn1H+NvOGNjRz49sAhRIjbvxX6goTCVo1ieMh+N5/vOdQRySNonFehfRCWMhlqYpBBo1meZ2vnhRT3c2AqmiNC90IvIJYR4GDktlpJSgMxREuLLu5s+g20oPifkjylZOruipksPg/5gPI1x3iiER8r3p0rAdJcvhQ6MvuSCzNsPRdhu9Uicg++KxkkielshUiCF64Jsr/HjgYiyne/eUFTVo31VqdxAIokFzgcrHzQ0v38Ktsmfh7K3xuQt19e/GLvyRHHmFwfsuCxmRbMR33Oxav4a2FwIMu6BfitZQEmQDZQtgCA4wq8iJmFQ2UhvmjY+kfD41bKc+U+jBw2ueWp2qYqc/ZoTFR8GbyGmsY5d0LCU3i+UAApoWP4MGXXD1vLv2Fd9CVl7l/ScfnMhqUzC/IRaG8xliacURcLsIUomJiqKSvXo=
  file_glob: true
  file: target/deploy/*
  skip_cleanup: true
  on:
    repo: gtasa-savegame-editor/gtasa-savegame-editor
    tags: true
