name: 🐧 Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jar:
    name: 🐧 .jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build jar
        run: mvn clean install -Dmaven.javadoc.skip=true -B -V
      - name: Create deploy directory
        run: mkdir deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Copy jar to deploy dir
        run: cp -v "savegame-editor/target/$(ls savegame-editor/target | grep jar-with-dependencies)" deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Attach binaries to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/*
          tag: ${{ github.ref }}
          overwrite: true
  deb:
    name: 🐧 .deb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build deb
        run: mvn clean install -Pdeb -Dmaven.javadoc.skip=true -B -V
      - name: Create deploy directory
        run: mkdir deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Copy deb to deploy dir
        run: cp -v "savegame-editor/target/$(ls savegame-editor/target | grep .deb)" deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Attach binaries to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/*
          tag: ${{ github.ref }}
          overwrite: true
  rpm:
    name: 🐧 .rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build rpm
        run: mvn clean install -Prpm -Dmaven.javadoc.skip=true -B -V
      - name: Create deploy directory
        run: mkdir deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Copy rpm to deploy dir
        run: cp -v "savegame-editor/target/rpm/savegame-editor/RPMS/noarch/$(ls savegame-editor/target/rpm/savegame-editor/RPMS/noarch | grep .rpm)" deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Attach binaries to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/*
          tag: ${{ github.ref }}
          overwrite: true
