name: Release

on:
  push:
    tags:
      - '*'

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['java']

    steps:
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ACCESS_TOKEN }}
