name: 🏢 Windows

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  exe:
    name: 🏢 .exe
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build exe
        run: mvn clean install -Pdeb "-Dmaven.javadoc.skip=true" -B -V -Pwindows
      - name: Create deploy directory
        run: mkdir deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Copy app to deploy dir
        run: copy "savegame-editor/target/*.exe" deploy
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Compress release
        run: Compress-Archive "deploy" "GTA-SA-Savegame-Editor.Windows.zip"
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GTA-SA-Savegame-Editor.Windows.zip
          asset_name: GTA-SA-Savegame-Editor.Windows.zip
          asset_content_type: application/zip
